### ISSUE TITLE
Please consider putting each sample in to its OWN repo to simplify use.

### ISSUE THREAD

**Issue by SimonDarksideJ** [Yecats/GameDevTutorials#25]
Please consider breaking up this awesome resource in to separate repos, there is just no need to group everything in one repo like this, it simply makes it harder / longer for readers to pick and choose what resources they want to learn from.

If you want to group the projects, then have one repo that uses Submodules to each of the independent samples.

Use Pages to link / describe all the different resources available.

There is no cost involved and it will make managing / maintaining the samples easier with only a little bit more effort.

Thanks.

**Comment by SimonDarksideJ** [comment]
Happy to help test and provide guidance

You could also use separate branches between the "Before" and "After" states, which then also show "what" changes were made rather than just a code dump alongside the article.

P.S. Going through the addressables tutorials atm (great job), but there were errors from Unity from just opening the starter project.

**Comment by tacman** [comment]
I've made this repo public, and am open to feedback on how to improve the structure:

https://github.com/FreeUnityProjects/Create-healthbar-ui-toolkit/tree/main

The main branch will need to contain the instructions.  There are 2 other branches, starter and final.  The idea for the workflow that I have is:

* Clone the repo
* git checkout final
* Open in Unity (I always want to see that the final code works with my version of Unity before starting a tutorial)
* close Unity
* git checkout starter
* Open Unity and begin the tutorial

Personally, I like to use the latest release of Unity, and I'd prefer that the repo is properly configured for that.  I started with some tools to automate this process.

**Comment by SimonDarksideJ** [comment]
One quick comment on that structure.  Your branch structure currently looks like:

Main
-> Starter
-> Final

Where I would recommend having

Main
-> Starter
     -> Final

Final should be a branch off starter, that way there is also a change history from Starter (where the reader beings) and Final (where they end up)

Hope that helps

**Comment by tacman** [comment]
Thanks, good idea.  Currently I'm creating a bash script like this, I'll tweak it as you suggest.  I also will put in a real README.md that links back to the original repo and directory, which is the primary reason I hadn't made these public.

There's also an issue with repositories with a space in the name not working.  And I'm sure a bunch of other stuff...

```bash
cd /home/tac/u/GameDevTutorials/tutorials/Unity/Get-started-with-behavior-trees/projects/starterProject
rm -Rf /home/tac/u/GameDevTutorials/tutorials/Unity/Get-started-with-behavior-trees/projects/starterProject/.git
/usr/bin/git init -b main /home/tac/u/GameDevTutorials/tutorials/Unity/Get-started-with-behavior-trees/projects/starterProject
/usr/bin/git remote add origin git@github.com:FreeUnityProjects/Get-started-with-behavior-trees.git
git add .gitignore README.md && git commit -m "initialize repo on main branch"
git branch -M main
git push --set-upstream origin main
cd /home/tac/u/GameDevTutorials/tutorials/Unity/Get-started-with-behavior-trees/projects/starterProject
git checkout -b starter && git branch
git push --set-upstream origin starter
git branch
git merge main && git add . && git commit -m "add starter"
git push && git branch
rm -Rf /home/tac/u/GameDevTutorials/tutorials/Unity/Get-started-with-behavior-trees/projects/finalProject/.git
mv /home/tac/u/GameDevTutorials/tutorials/Unity/Get-started-with-behavior-trees/projects/starterProject/.git /home/tac/u/GameDevTutorials/tutorials/Unity/Get-started-with-behavior-trees/projects/finalProject/.git
cd /home/tac/u/GameDevTutorials/tutorials/Unity/Get-started-with-behavior-trees/projects/finalProject
git merge starter
cd /home/tac/u/GameDevTutorials/tutorials/Unity/Get-started-with-behavior-trees/projects/finalProject
git checkout -b final && git branch
git push --set-upstream origin final
git branch
git merge starter && git add . && git commit -m "add final"
git push && git branch
cd /home/tac/u/GameDevTutorials/tutorials/Unity/Get-started-with-behavior-trees/projects/finalProject
git checkout main && git branch
git branch
git merge final && git add . && git commit -m "add main"
git push && git branch
```

**Comment by SimonDarksideJ** [comment]
If you are completely starting the repo from scratch, then skip over creating a main branch, just create the starter branch.  It's unlikely you will be using main anyway.

Just have Starter with Final branched off starter, then set the default github branch to Final (or starter), just ensure the readme for the repo is the same in both (only ever edit the readme in starter then merge that up to final).

As for spaces, yeah, do not do that, markdown files can have spaces, but not repos or branches :D

**Comment by tacman** [comment]
Yeah, good idea.

Here's another one, with the starter/final only:

https://github.com/FreeUnityProjects/Get-started-with-behavior-trees

Still need to tweak the readme, and confirm that it loads.

**Comment by SimonDarksideJ** [comment]
Looks good, but "appears" that Starter is branched from Final, rather than final being branches from starter, but I could be reading that wrong.

Usually github states branches are ahead/behind the source branch. but starter shows as one commit behind final.  But that "could" be because final is default.

**Comment by Yecats** [comment]
@SimonDarksideJ - first, I feel a bit star struck. ;) 

I agree that this doesn't scale well and am planning on pulling them apart over the weekend. I've also started renaming the projects so that they're more descriptive than "starter" and "final". (I find that annoying in the Hub myself...)

**Comment by tacman** [comment]
@Yecats  how can I help?  I've done a bunch of grunt work to standardize the tutorial directory as single repos: https://github.com/FreeUnityProjects

I wish there were a way to reference a file by name, rather than the guid.  The guid and .meta files are tied together, and in the current system, they are indeed two completely separate projects, so always unique guids.  

Thoughts on where to put the "articles"?  Could easily go into the start project, and not change, but could also go into github pages.

**Comment by SimonDarksideJ** [comment]
Well, if the articles are written in markdown, they could be the readme, although personally, the Readme should just be a synopsis that links back to the article.

In my new GitHub Pages site, the theme allows me to inject a GitHub repo link into the article which makes it easier.

I'd recommend having a single repo per article (or series), if you then want a catalogue of samples to download, either have a single page listing them all in the article site or create an additional repo which just contains a set of submodules to each sample repo, combining them all.

But in my experience, most people search and want to read up on a particular area rather than reading all the content on a site.  So keeping the focus per article is better to reduce any friction on getting that content.

**Comment by SimonDarksideJ** [comment]
> I'm hesitant to drive the functionality based on the branch because I want to make this a low barrier of entry for folks not deeply familiar with VCS.

Simply having the "final" project as the default branch, means they get access to the complete sample straight away.  And it's only a few instructions to show them how to switch branches to do it manually.

**Comment by tacman** [comment]
> Simply having the "final" project as the default branch, means they get access to the complete sample straight away. And it's only a few instructions to show them how to switch branches to do it manually.

Indeed, my workflow when walking through a tutorial is always to start at the end, to see what it is I'm going to learn and make sure it works (there are _many_ tutorials where the final code doesn't immediately work with the current/latest versions of Unity).  After I've confirmed that the final code works and is something I want to learn, I switch to the starting code and begin the tutorial.

To that end, I've started to add

```console
/home/tac/Unity/Hub/Editor/2021.2.18f1/Editor/Unity -accept-apiupdate -quit -batchmode -projectPath . -buildLinux64Player Builds/player -logFile Builds/build.log -buildTarget Linux64
```

to the script that creates these repositories, but now am not sure how to incorporate that into the branches.  For example, 
https://github.com/FreeUnityProjects/Create-healthbar-ui-toolkit was created with 2020.3.4f1, so the branch names could be starter-2020.3, final-2020.3, etc.  This is even more relevant when testing the beta versions.

**Comment by Yecats** [comment]
All the tutorials are broken out into their own repo here and some what cleaned up. I still need to upgrade some of the older ones, fix the addressable issue referenced in the other ticket, and redirect from the tutorial site, so I can't retire this one yet... 

https://github.com/gamedev-resources

**Comment by Yecats** [comment]
Closing - the new organization is setup and all tutorials are pointed over.
